[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-cli
monitor_speed = 115200
lib_deps =
  jgromes/RadioLib@7.7.1
build_flags =
  -I../include
  -I../protocol/include

[env:tx]
extends = env:teensy41
build_flags =
  ${env:teensy41.build_flags}
  -D NURA_BENCH_ENABLE_TX=1
