[env]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-cli
monitor_speed = 115200
lib_deps =
  sandeepmistry/LoRa@^0.8.0
  Wire
build_flags =
  -I../include
  -I../protocol/include

[env:teensy41]

[env:sx1276_ground]
build_flags =
  ${env.build_flags}
  -D NURA_GROUND_SX1276=1

[env:sx1276_ground_probe]
build_flags =
  ${env.build_flags}
  -D NURA_FORCE_FLIGHT_FREQ=1

[env:flight_pcb_sx127x]
build_flags =
  ${env.build_flags}
  -D NURA_FLIGHT_PCB_SX127X=1

[env:pair_test]
build_flags =
  ${env.build_flags}
  -D NURA_RECEIVER_AUTO_COMMAND_TEST=1
